import Head from "next/head";
import Image from "next/image";
import AreaChart from "../components/AreaChart";
import FirstCard from "../components/FirstCard";
import FourthCard from "../components/FourthCard";
import Navbar from "../components/Navbar";
import SecondCard from "../components/SecondCard";
import Tabs from "../components/Tabs";
import ThirdCard from "../components/ThirdCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>TweeVest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar />
        <Tabs />
        {/* CARDS SECTION */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-2xl mx-auto  lg:max-w-none">
            <div className="mt-10 space-y-12 md:space-y-0  md:grid md:grid-cols-2  md:gap-x-4 lg:space-y-0 lg:grid lg:grid-cols-4 lg:gap-x-6 ">
              <FirstCard />
              <SecondCard />
              <ThirdCard />
              <FourthCard />
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-16">
          {/* filter SECTION */}
          <div className="bg-white shadow-xl rounded-md  h-14 mt-5 flex flex-row items-center pl-3 border-2  border-gray-100">
            <div className="bg-gray-300 rounded-2xl flex flex-row justify-between px-2 py-1 mx-1">
              <h1 className="text-gray-500 mr-3 ml-1">Earning Growth</h1>
              <Image alt=""
                src={"/close-circle.svg"}
                width={20}
                height={20}
                className="cursor-pointer"
              />
            </div>
            <div className="bg-gray-300 rounded-2xl flex flex-row justify-between px-2 py-1 mx-1">
              <h1 className="text-gray-500 mr-3 ml-1">Sales Growth</h1>
              <Image alt=""
                src={"/close-circle.svg"}
                width={20}
                height={20}
                className="cursor-pointer"
              />
            </div>
            <div className="bg-blue-500 rounded-2xl flex flex-row justify-between px-2 py-1 mx-1">
              <h1 className="text-white mr-3 ml-1">Add</h1>
              <Image alt=""
                src={"/add-circle.svg"}
                width={20}
                height={20}
                className="cursor-pointer"
              />
            </div>
          </div>
          {/* LAST SECTION */}
          {/* LEFT SECTION */}
          <div className="mt-10 flex flex-row md:flex-col lg:flex-row">
            <div className="w-fit ">
              {/* FIRST ROW */}
              <div className="flex flex-row justify-between my-4 ">
                <div className="flex flex-row items-center">
                  <h1 className="text-blue-900 font-bold mr-2">
                    Fundamentals Snapshot
                  </h1>
                  <Image alt="" src={"/info-circle.svg"} width={15} height={15} />

                  <div className="h-2 w-7 bg-gray-300 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                  <h1 className="text-xs text-blue-900 font-semibold ml-1">
                    Current
                  </h1>
                  <div className="h-2 w-7 bg-blue-100 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                  <h1 className="text-xs text-blue-900 font-semibold ml-1">
                    Estimates
                  </h1>
                </div>
                <div className="bg-gray-200 flex flex-row items-center justify-center px-3 py-2 rounded-md">
                  <Image alt="" src={"/activity.svg"} width={10} height={10} />
                  <h1 className="text-blue-900 font-semibold text-xs ml-2">
                    Show Graph
                  </h1>
                </div>
              </div>
              <div className="flex flex-row">
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>{" "}
                <div className="flex flex-col justify-center items-center mx-1">
                  <h1 className="font-semibold text-blue-900 text-xs mb-1">
                    Q1.19
                  </h1>
                  <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                    <h1 className="font-semibold text-green-400 text-xs">
                      +58%
                    </h1>
                    <h1
                      className="font-semibold text-gray-400"
                      style={{ fontSize: "10px" }}
                    >
                      1.58 vs 1
                    </h1>
                  </div>
                </div>
              </div>
              {/* SECOND ROW */}
              <div className="w-fit my-5">
                <div className="flex flex-row justify-between my-3">
                  <div className="flex flex-row items-center ">
                    <h1 className="text-blue-900 font-bold mr-2">
                      Sales Growth
                    </h1>
                    <Image alt="" src={"/info-circle.svg"} width={15} height={15} />

                    <div className="h-2 w-7 bg-gray-300 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Current
                    </h1>
                    <div className="h-2 w-7 bg-blue-100 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Estimates
                    </h1>
                  </div>
                  <div className="bg-gray-200 flex flex-row items-center justify-center px-3 py-2 rounded-md">
                    <Image alt="" src={"/activity.svg"} width={10} height={10} />
                    <h1 className="text-blue-900 font-semibold text-xs ml-2">
                      Show Graph
                    </h1>
                  </div>
                </div>
                <div className="flex flex-row">
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        +58%
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
              {/* THIRD ROW */}
              <div className="w-fit my-5">
                <div className="flex flex-row justify-between my-3">
                  <div className="flex flex-row items-center ">
                    <h1 className="text-blue-900 font-bold mr-2">
                      Return on Equity
                    </h1>
                    <Image alt="" src={"/info-circle.svg"} width={15} height={15} />

                    <div className="h-2 w-7 bg-gray-300 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Current
                    </h1>
                    <div className="h-2 w-7 bg-blue-100 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Estimates
                    </h1>
                  </div>
                  <div className="bg-gray-200 flex flex-row items-center justify-center px-3 py-2 rounded-md">
                    <Image alt="" src={"/activity.svg"} width={10} height={10} />
                    <h1 className="text-blue-900 font-semibold text-xs ml-2">
                      Show Graph
                    </h1>
                  </div>
                </div>
                <div className="flex flex-row">
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/dec.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/dec.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
              {/* FOURTH ROW */}
              <div className="w-fit my-5">
                <div className="flex flex-row justify-between my-3">
                  <div className="flex flex-row items-center ">
                    <h1 className="text-blue-900 font-bold mr-2">
                      Institutionnal Ownership
                    </h1>
                    <Image alt="" src={"/info-circle.svg"} width={15} height={15} />

                    <div className="h-2 w-7 bg-gray-300 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Current
                    </h1>
                    <div className="h-2 w-7 bg-blue-100 border-gray-400 border-2 ml-4 rounded-lg mt-1"></div>
                    <h1 className="text-xs text-blue-900 font-semibold ml-1">
                      Estimates
                    </h1>
                  </div>
                  <div className="bg-blue-700 flex flex-row items-center justify-center px-3 py-2 rounded-md">
                    <Image alt="" src={"/white-activity.svg"} width={10} height={10} />
                    <h1 className="text-white font-semibold text-xs ml-2">
                      Show Graph
                    </h1>
                  </div>
                </div>
                <div className="flex flex-row">
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/dec.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/dec.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col justify-center items-center mx-1">
                    <h1 className="font-semibold text-blue-900 text-xs mb-1">
                      Q1.19
                    </h1>
                    <div className="bg-gray-200 w-14 h-12 rounded-md flex flex-col items-center justify-center">
                      <h1 className="font-semibold text-green-400 text-xs">
                        <Image alt="" src={"/inc.svg"} width={15} height={15} />
                      </h1>
                      <h1
                        className="font-semibold text-gray-400"
                        style={{ fontSize: "10px" }}
                      >
                        1.58 vs 1
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* RIGHT SECTION */}
            <div className="p-3 w-full">
              <div
                className="bg-white shadow rounded-md p-4"
                style={{ height: "80vh" }}
              >
                <AreaChart />
              </div>
            </div>
          </div>
        </div>

        <footer className="mt-44 relative">
          <div className="w-full bg-blue-900 h-56 flex items-end">
            <div className="flex flex-row justify-between w-full mb-3">
              <Image alt="" src={"/TweeVest_Logo.svg"} width={150} height={30} />
              <span className="text-white font-semibold text-sm">
                © 2022 TweeVest. All rights reserved
              </span>
              <div className="flex flex-row justify-between  w-32 pr-4">
                <Image alt="" src={"/social1.svg"} width={20} height={30} />
                <Image alt="" src={"/social2.svg"} width={20} height={30} />
                <Image alt="" src={"/social3.svg"} width={20} height={30} />
                <Image alt="" src={"/social4.svg"} width={20} height={30} />
              </div>
            </div>
          </div>
          <div className="w-full absolute bottom-32 flex justify-center ">
            <div className="relative w-2/3 lg:w-1/2 sm:w-fit bg-blue-500 px-5 flex flex-col items-center h-44 justify-center rounded-lg">
              <div className="hidden md:block absolute left-0">
                <Image alt=""
                  src={"/left-footer.svg"}
                  height={150}
                  width={150}
                />
              </div>
              <div className="hidden md:block absolute right-0 bottom-0">
                <Image alt=""
                  src={"/footer-right.svg"}
                  height={140}
                  width={140}
                />
              </div>
              <h1 className="text-white text-xl font-semibold mb-4 ">
                New Feature Coming Soon, Stay Tuned!
              </h1>
              <div className="max-w-md mx-auto rounded-lg overflow-hidden md:max-w-xl bg-transparent border-white border-2">
                <div className="md:flex">
                  <div className="w-full ">
                    <div className="flex flex-row">
                      {" "}
                      <input
                        type="text"
                        className="bg-transparent  text-white w-full px-4 pr-20 rounded-md focus:outline-none "
                        name=""
                      />
                      <button className="h-10 rounded  text-sm right-2 px-3 w-fit bg-white text-blue-500 ">
                        Subscribe
                      </button>{" "}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </>
    </>
  );
}
